name: test if conditions

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: 'Branch to use'
        required: true
        type: choice
        options:
        - master
        - dev

jobs:
  test-conditions:
    runs-on: ubuntu-latest

    steps:
      - name: simple evaluation on dev
        if: github.ref == 'refs/heads/dev'
        run: echo "dev branch runs"
        
      - name: simple evaluation on master
        if: github.ref == 'refs/heads/master'
        run: echo "master branch running"
